Sudoku - Generator

In [1]:
import numpy as np
import random

In [2]:
serie = np.array(range(9))
serie = serie + 1
serie

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.random.shuffle(serie)
serie

array([1, 4, 3, 8, 6, 5, 9, 2, 7])

In [4]:
field = np.zeros([9,9],dtype=np.int8)
field[0] = serie
field

array([[1, 4, 3, 8, 6, 5, 9, 2, 7],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [5]:
weights = np.array([])
weights = np.array(range(0,9))
weights = 10**weights
weights = np.insert(weights, 0, 0)
weights

array([        0,         1,        10,       100,      1000,     10000,
          100000,   1000000,  10000000, 100000000], dtype=int32)

In [6]:
def winones(obj, position):
    x = int(position / 3)
    for x in range(3*x,3*x+3):
        y = int(position % 3)
        for y in range(3*y,3*y+3):
            obj[x,y] = 1

In [7]:
window = np.zeros([9,9], dtype=np.int8)
winones(window, 0)
window

array([[1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [8]:
def testwin(obj, position):
    window = np.zeros([9,9], dtype=np.int8)
    winones(window, position)
    window = window * -1
    z = obj & window
    return z

In [9]:
z = testwin(field, 0)
z

array([[1, 4, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [10]:
(weights[z])

array([[   1, 1000,  100,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int32)

In [11]:
np.sum(weights[z])

1101

In [12]:
np.random.shuffle(serie)
field[1] = serie
np.random.shuffle(serie)
field[2] = serie

In [13]:
field

array([[1, 4, 3, 8, 6, 5, 9, 2, 7],
       [7, 6, 4, 2, 3, 8, 5, 9, 1],
       [5, 4, 2, 1, 3, 7, 8, 9, 6],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [14]:

while(True):
    np.random.shuffle(serie)
    field[1] = serie
    np.random.shuffle(serie)
    field[2] = serie
    if(weights[testwin(field, 0)].sum() == 111111111):
        if(weights[testwin(field, 1)].sum() == 111111111):
            if(weights[testwin(field, 2)].sum() == 111111111):
                break


In [15]:
field

array([[1, 4, 3, 8, 6, 5, 9, 2, 7],
       [6, 8, 2, 9, 3, 7, 5, 4, 1],
       [9, 5, 7, 4, 1, 2, 3, 8, 6],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [16]:
def vmatch(obj, row):
    m=0
    while(m < row):
        for x in range(0,9):
            if(obj[row][x] == obj[m][x]):
                return False
        m += 1
    return True


In [23]:
import numpy as np
p = 3
l = p // 3
m = p % 3
a = np.zeros((3,9))
while(m < 3):
    for x in range(0, 3):
        for y in range(0, 3):
            a[m][3*y+x] = field[3*l+y][3*m+x]
    m += 1


a

array([[2., 1., 8., 7., 6., 4., 6., 8., 7.],
       [3., 9., 4., 9., 3., 2., 4., 9., 5.],
       [7., 6., 5., 1., 5., 8., 3., 1., 2.]])

In [18]:
def wmatch(obj, maxwin):
    '''
    maxwin values:
    3, 6, 9

    '''
    l = l // 3
    m = m % 3
    a = np.zeros((3,9))
    while(m < maxwin):
        for x in range(0, 3):
            for y in range(0, 3):
                a[m][3*y+x] = field[3*l+y][3*m+x]
        m += 1

    m = maxwin - 3
    while(m < maxwin):
        for k in range(0, 9):
            for n in range(0, k-1):
                if(a[n] == a[k]):
                    return False
        m += 1
    return True




In [19]:
while(True):
    np.random.shuffle(serie)
    field[3] = serie
    if vmatch(field, 3):
        break

field

array([[1, 4, 3, 8, 6, 5, 9, 2, 7],
       [6, 8, 2, 9, 3, 7, 5, 4, 1],
       [9, 5, 7, 4, 1, 2, 3, 8, 6],
       [2, 1, 8, 3, 9, 4, 7, 6, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [21]:
while(True):
    np.random.shuffle(serie)
    field[4] = serie
    np.random.shuffle(serie)
    field[5] = serie
    if wmatch(field, 6):
        break

field

UnboundLocalError: local variable 'l' referenced before assignment